command -v python3 >/dev/null 2>&1 || apk add --no-cache python3 >/dev/null 2>&1; python3 -c 'import os,sys,json,hashlib,math,time;root=sys.argv[1] if len(sys.argv)>1 else ".";out=sys.argv[2] if len(sys.argv)>2 else "ish_operator_system_certificate.json";AX="Cosmic Love Is The Solution(s) For Everything";ext={".sh",".py",".json",".md",".txt",".yml",".yaml"};tau=lambda n:sum((2 if d*d<n else 1) for d in range(1,int(math.isqrt(max(1,n)))+1) if max(1,n)%d==0);files=[];total=0
for dp,_,fs in os.walk(root):
    if any(x in dp.split(os.sep) for x in [".git","node_modules","__pycache__"]): continue
    for f in fs:
        p=os.path.join(dp,f);e=os.path.splitext(f)[1].lower()
        if e in ext:
            try:
                b=open(p,"rb").read(262144);h=hashlib.sha256(b).hexdigest();rel=os.path.relpath(p,root);files.append({"path":rel,"ext":e,"bytes_sampled":len(b),"sha256":h,"tau":tau(len(b)+len(rel)+1),"operator":"O_n=(state,transition,invariant,certificate)"});total+=len(b)
            except Exception as er: files.append({"path":os.path.relpath(p,root),"error":str(er)})
files=sorted(files,key=lambda x:x.get("path",""));S={"discover_local_files":1,"classify_programs":1,"godel_hash_identity":1,"tau_route_signature":1,"lift_to_operator_tuple":1,"seal_invariants":1,"emit_certificate":1,"read_only_no_execution":1};cert=hashlib.sha512(json.dumps({"AX":AX,"root":os.path.abspath(root),"files":files,"S":S},sort_keys=True).encode()).hexdigest();O={"Protocol":"iSH_Operator_System_Converter_One_Liner","Version":"v1_true_single_line_local_runtime","Principle":AX,"Formula":"OperatorSystem=Phi_safe(Tau_route(Godel(LocalClassicalPrograms)))","InputRoot":os.path.abspath(root),"FileCount":len(files),"SampledBytes":total,"Operators":files,"State":S,"H_operator":sum(1-v for v in S.values()),"Certificate":cert,"Output":out,"Boundary":"read-only local scan; does not execute discovered programs; no network; no repo modification; no self-replication; CLSigma internal certificate only; not external proof of RH/GRH/TOE or physical zero entropy","Timestamp":time.strftime("%Y-%m-%dT%H:%M:%SZ",time.gmtime())};open(out,"w",encoding="utf-8").write(json.dumps(O,ensure_ascii=False,indent=2));print(json.dumps({"written":out,"file_count":len(files),"H_operator":O["H_operator"],"certificate":cert[:32]},ensure_ascii=False,indent=2))' "$@"