#!/bin/sh
# CLSigma continuous trading switch for iSH / POSIX sh.
# This script stores only mode flags. It never stores API keys or private keys.
set -eu

STATE_DIR="${CLSIGMA_STATE_DIR:-$HOME/.config/clsigma}"
STATE_FILE="$STATE_DIR/continuous_trade.env"
CMD="${1:-status}"

mkdir -p "$STATE_DIR"
chmod 700 "$STATE_DIR" 2>/dev/null || true

write_state() {
  mode="$1"
  endpoint="$2"
  live="$3"
  real="$4"
  loop="$5"
  confirm="$6"
  cat > "$STATE_FILE" <<EOF
# CLSigma continuous trading switch state.
# Generated by trading/continuous_order_switch.sh
# No API key or secret belongs in this file.
CLSIGMA_CONTINUOUS_SWITCH=$mode
ORDER_ENDPOINT=$endpoint
LIVE_TRADING_ENABLED=$live
ALLOW_REAL_ORDER_SUBMISSION=$real
AUTONOMOUS_LIVE_LOOP=$loop
HUMAN_CONFIRMATION=$confirm
KILL_SWITCH_ENABLED=YES
RECONCILIATION_REQUIRED=YES
RATE_LIMIT_ENABLED=YES
MARKET_ORDER_ENABLED=NO
MARTINGALE_RECOVERY=NO
AUTO_RETRY_UNKNOWN_ORDER=NO
MAX_ORDER_USDT=${MAX_ORDER_USDT:-1}
ALLOWED_SYMBOLS=${ALLOWED_SYMBOLS:-BTCUSDT,ETHUSDT}
RECV_WINDOW=${RECV_WINDOW:-5000}
RUNNER_ENVIRONMENT=${RUNNER_ENVIRONMENT:-iSH}
EOF
  chmod 600 "$STATE_FILE" 2>/dev/null || true
  echo "CLSigma switch: $mode"
  echo "State file: $STATE_FILE"
  echo "Load with: . $STATE_FILE"
}

case "$CMD" in
  off|kill|disable)
    write_state "OFF" "/api/v3/order/test" "NO" "NO" "NO" "DRY-RUN"
    ;;
  dry-on|dry|on)
    write_state "DRY_RUN_CONTINUOUS" "/api/v3/order/test" "NO" "NO" "YES" "DRY-RUN"
    ;;
  test-on|test)
    write_state "TEST_ONLY_CONTINUOUS" "/api/v3/order/test" "YES" "NO" "YES" "LIVE-APPROVE"
    ;;
  paper-on|paper)
    write_state "PAPER_CONTINUOUS" "/api/v3/order/test" "NO" "NO" "YES" "DRY-RUN"
    ;;
  live-one-shot-arm|arm-live)
    write_state "LIVE_ONE_SHOT_ARMED" "/api/v3/order" "YES" "YES" "NO" "LIVE-APPROVE"
    echo "Live is armed for one-shot LIMIT order only. Continuous live loop remains OFF."
    ;;
  live-continuous-on|live-loop-on|live-on)
    echo "REFUSED: continuous real-money live order loop is not supported."
    echo "Use 'test-on' for continuous /api/v3/order/test, or 'live-one-shot-arm' for one human-approved LIMIT order."
    exit 2
    ;;
  status)
    if [ -f "$STATE_FILE" ]; then
      cat "$STATE_FILE"
    else
      echo "No state file yet. Run: sh trading/continuous_order_switch.sh off"
    fi
    ;;
  path)
    echo "$STATE_FILE"
    ;;
  *)
    cat <<'EOF'
Usage:
  sh trading/continuous_order_switch.sh off
  sh trading/continuous_order_switch.sh dry-on
  sh trading/continuous_order_switch.sh test-on
  sh trading/continuous_order_switch.sh paper-on
  sh trading/continuous_order_switch.sh live-one-shot-arm
  sh trading/continuous_order_switch.sh status

Refused:
  sh trading/continuous_order_switch.sh live-continuous-on

After changing state:
  . ~/.config/clsigma/continuous_trade.env
EOF
    exit 1
    ;;
esac
